#!/usr/bin/env sh

#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.5
yabai -m config window_border                on
yabai -m config window_border_width          3
#yabai -m config active_window_border_color   0xff775759
#yabai -m config normal_window_border_color   0xff505050
#yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_border_color   0xffcc00cb
yabai -m config insert_window_border_color   0xff8E83B8
yabai -m config normal_window_border_color   0xff8E83B8
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp # bsp or float
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6

yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Calculator" manage=off
yabai -m rule --add app="Calendar" manage=off
yabai -m rule --add app="Mucis" manage=off
yabai -m rule --add app="System Preferences" manage=off layer=above
yabai -m rule --add app="Preferences$" manage=off layer=above
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="System Information" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="Alfred Preferences" manage=off
yabai -m rule --add app="^Bitwarden" manage=off
yabai -m rule --add app="IntelliJ IDEA" manage=off
yabai -m rule --add app="IntelliJ IDEA" title=".*\[(.*)\].*" manage=on
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="Signal" manage=off
yabai -m rule --add app="The Unarchiver" manage=off
yabai -m rule --add app="^Yubico" manage=off

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"


echo "yabai configuration loaded.."
